version: '3'
services:
  postgres_django:
    image: postgres:latest
    environment:
      POSTGRES_DB: openmonitor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_django:/var/lib/postgresql/data
    networks:
      - openmonitor_network

  django:
    build:
      context: ./OpenMonitor/django_app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./OpenMonitor/django_app:/app
    environment:
      POSTGRES_DB: openmonitor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres_django
    ports:
      - "8000:8000"
    depends_on:
      - postgres_django
    networks:
      - openmonitor_network

  vue:
    build:
      context: ./OpenMonitor/vue_frontend
      dockerfile: Dockerfile
    volumes:
      - ./OpenMonitor/vue_frontend/src:/app/src
      - ./OpenMonitor/vue_frontend/package.json:/app/package.json
    ports:
      - "5174:5174"
    networks:
      - openmonitor_network

  nginx:
    build:
      context: ./OpenMonitor/nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /home/webugr/openssl/ofiwebsubdir:/etc/ssl/certs
    depends_on:
      - django
      - vue
    networks:
      - openmonitor_network




volumes:
  postgres_data_django:

networks:
  openmonitor_network:
