# Usar la imagen oficial de Nginx
FROM nginx:latest

# Copiar el archivo de configuración de Nginx al contenedor
COPY ./nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80 para el tráfico HTTP
EXPOSE 80
